// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"database/sql"
	"time"
)

type User struct {
	ID              int32         `json:"id"`
	Name            string        `json:"name"`
	Email           string        `json:"email"`
	IsEmailVerified bool          `json:"is_email_verified"`
	Otp             sql.NullInt32 `json:"otp"`
	OtpExpiry       sql.NullTime  `json:"otp_expiry"`
	Password        string        `json:"password"`
	Username        string        `json:"username"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
}
