// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"database/sql"
	"time"
)

type User struct {
	ID              int32
	Name            string
	Email           string
	IsEmailVerified bool
	Otp             sql.NullString
	OtpExpiry       sql.NullTime
	Password        string
	Username        string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
